# Generated by Django 5.1.2 on 2024-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_attendance_status_alter_attendance_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_khr', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('relationship', models.CharField(choices=[('Wife', 'Wife'), ('Husband', 'Husband')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Morning', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
