# Generated by Django 5.1.2 on 2025-01-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_commune_district_province_alter_person_price_khr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='commune_kh_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='district_kh_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='province_kh_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='village_kh_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
