# Generated by Django 5.2.4 on 2025-08-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_person_commune_kh_name_person_district_kh_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='commune_kh_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='district_kh_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='province_kh_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='village_kh_name',
        ),
    ]
